version: "3.2"

services:
  nginx:
    image: nginx
    container_name: nhannd_nginx
    volumes:
      - ./source:/www
      - ./source/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "88:80"
  php-fpm:
    container_name: nhannd_php_fpm
    build:
        context: ./docker
        dockerfile: dockerfile
    working_dir: /www
    volumes:
      - ./source:/www
  mysql:
    image: mysql:5.7
    container_name: nhannd_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'nhannd'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - "33066:3306"
