version: "3.2"

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./source:/www
      - ./source/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "88:80"
  php-fpm:
    container_name: php_fpm
    build:
        context: ./docker
        dockerfile: dockerfile
    working_dir: /www
    volumes:
      - ./source:/www
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'laravel'
    ports:
      - "33066:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
